apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aichatapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GeraldAkenji/AI-Chat.git
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true